version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: ppdrive_db
    environment:
      POSTGRES_PASSWORD: ${PPDRIVE_DB_PASSWORD}
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppdrive_app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${PPDRIVE_DB_USER}:${PPDRIVE_DB_PASSWORD}@db:5432/${PPDRIVE_DB_NAME}
      PPDRIVE_AUTH_URL: ${PPDRIVE_AUTH_URL}
      PPDRIVE_PORT: ${PPDRIVE_PORT}
      PPDRIVE_ALLOW_URL: ${PPDRIVE_ALLOW_URL}
      DEBUG_MODE: ${DEBUG_MODE}
      
    depends_on:
      - db

    ports:
      - ${PPDRIVE_PORT}:${PPDRIVE_PORT}

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
