services:
  ppdrive_db:
    image: postgres:latest
    container_name: ppdrive_db
    environment:
      POSTGRES_USER: ${PPDRIVE_DB_USER}
      POSTGRES_PASSWORD: ${PPDRIVE_DB_PASSWORD}
      POSTGRES_DB: ${PPDRIVE_DB_NAME}
      PPDRIVE_DB_PORT: ${PPDRIVE_DB_PORT}

    ports:
      - ${PPDRIVE_DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  ppdrive:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppdrive_app
    restart: unless-stopped
    image: prodbyola/ppdrive:latest
    environment:
      DATABASE_URL: postgres://${PPDRIVE_DB_USER}:${PPDRIVE_DB_PASSWORD}@ppdrive_db:5432/${PPDRIVE_DB_NAME}
      PPDRIVE_AUTH_URL: ${PPDRIVE_AUTH_URL}
      PPDRIVE_PORT: ${PPDRIVE_PORT}
      PPDRIVE_ALLOWED_ORIGINS: ${PPDRIVE_ALLOWED_ORIGINS}
      DEBUG_MODE: false

    depends_on:
      - ppdrive_db

    ports:
      - ${PPDRIVE_PORT}:${PPDRIVE_PORT}

    volumes:
      - ppdrive_data:/app

    networks:
      - app_network

volumes:
  postgres_data:
  ppdrive_data:

networks:
  app_network:
    driver: bridge
