services:
  ppdrive_redis:
    image: redis:7-alpine
    container_name: ppdrive_redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_network

  ppdrive_db:
    image: postgres:17-alpine
    container_name: ppdrive_db
    env_file: .env.docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  ppdrive:
    image: prodbyola/ppdrive:latest
    container_name: ppdrive_app
    restart: unless-stopped
    env_file: .env.docker
    environment:
      PPDRIVE_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ppdrive_db:5432/${POSTGRES_DB}
    depends_on:
      ppdrive_db:
        condition: service_healthy
      ppdrive_redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ppdrive_data:/app/data
    networks:
      - app_network

volumes:
  postgres_data:
  ppdrive_data:

networks:
  app_network:
    driver: bridge
