openapi: 3.1.0

info:
  title: PPDRIVE DOCUMENTATION
  version: 0.0.1
  summary: Intgratable File Manager
  description: |
    PPDRIVE is a powerful, standalone file manager written in Rust,
    designed for seamless integration into other applications
    via a RESTful API.

paths:
  /{asset_path}:
    get:
      deprecated: false
      summary: Serve an asset (file or folder) from the provided asset path.
      parameters:
        - in: path
          name: asset_path
          schema:
            type: string
          description: |
            This either the asset's original path or a custom_path set when
            the asset was created.

  /client/user/register:
    post:
      deprecated: false
      summary: Register a new user
      tags:
        - client

tags:
  - client:
    name: Client
    description: |
      Client routes are accesible only to a verifiable PPDRIVE `Client`.
      A client is an external application capable of authorizing users
      and managing assets on PPDRIVE.

      To access these routes, you need to provide your client's `token`
      by adding the token to `x-ppd-client` header of your requests.
      You can generate a client token by running `ppdrive create_client
      {client_name}` or via the Admin UI.
