[package]
name = "ppdrive_cli"
edition.workspace = true
version.workspace = true

[[bin]]
name = "ppdrive"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["rt", "fs"] }
ppdrive.workspace = true
anyhow.workspace = true
serde_json.workspace = true
ureq = "3"
flate2 = "1"
tar = "0.4"
