[package]
name = "ppdrive"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util = { workspace = true }
clap = { workspace = true, features = ["derive"] }
ppd_shared.workspace = true
