[package]
name = "ppdrive"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.35.1", features = ["io-std", "rt-multi-thread"] }
libloading = "0.8.8"
ppd_rest = { path = "../servers/rest" }
clap = "4.5.45"
