[package]
name = "client_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
chacha20poly1305 = "0.10.1"
hex = "0.4.3"
ppd_bk = { path = "../bookkeeper" }
ppd_shared = { path = "../../shared" }
uuid = "1.18.0"
