//! Database abstraction layer.
//!
//! Wraps sqlx [`AnyPool`] to support SQLite, PostgreSQL, and MySQL backends.
//! Handles connection setup, migrations, and engine-specific placeholder syntax.

use std::ops::Deref;
use std::str::FromStr;
use std::time::Duration;
use sqlx::{AnyPool, migrate};
use sqlx::migrate::Migrator;
use sqlx::pool::PoolOptions;
use sqlx::any::install_default_drivers;
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions};

pub mod asset;
pub mod bucket;
pub mod client;
pub mod user;

pub type DbPool = AnyPool;

#[derive(Clone)]
pub struct Database {
    pool: DbPool,
    engine: DbEngine,
}

impl Database {
    /// Create a new database connection pool, run migrations, and detect the engine type.
    pub async fn new(url: &str, max_connections: u32) -> anyhow::Result<Self> {
        install_default_drivers();

        let engine = if url.starts_with("postgres") {
            DbEngine::Postgres
        } else if url.starts_with("mysql") {
            DbEngine::Mysql
        } else {
            DbEngine::Sqlite
        };

        // For SQLite, resolve relative paths against root_dir so the DB
        // location is predictable regardless of the working directory.
        let url = match engine {
            DbEngine::Sqlite => resolve_sqlite_url(url)?,
            _ => url.to_string(),
        };

        if matches!(engine, DbEngine::Sqlite) {
            create_sqlite(&url).await?;
        }

        let pool = PoolOptions::new()
            .max_connections(max_connections)
            .acquire_timeout(Duration::from_secs(10))
            .idle_timeout(Duration::from_secs(300))
            .max_lifetime(Duration::from_secs(1800))
            .connect(&url)
            .await?;

        match engine {
            DbEngine::Mysql => run_mysql_migrations(&pool).await?,
            DbEngine::Postgres => run_postgres_migrations(&pool).await?,
            _ => migrate!("../migrations").run(&pool).await?,
        };

        Ok(Self { pool, engine })
    }

    /// Return the engine-specific placeholder (`?` for MySQL, `$N` otherwise).
    pub fn placeholder(&self, idx: u8) -> String {
        match self.engine {
            DbEngine::Mysql => "?".to_string(),
            _ => format!("${idx}")
        }
    }
}

impl Deref for Database {
    type Target = DbPool;

    fn deref(&self) -> &Self::Target {
        &self.pool
    }
}

#[derive(Clone, PartialEq, Eq)]
pub enum DbEngine {
    Sqlite,
    Postgres,
    Mysql,
}

/// If the URL is a relative SQLite path, resolve it against [`crate::root_dir()`].
fn resolve_sqlite_url(url: &str) -> anyhow::Result<String> {
    if let Some(path) = url.strip_prefix("sqlite:")
        && !path.starts_with('/') && path != ":memory:"
    {
        let root = crate::root_dir()?;
        let resolved = root.join(path);
        return Ok(format!("sqlite:{}", resolved.display()));
    }
    Ok(url.to_string())
}

/// Forces the creation of sqlite file (in case the URL is a file) and enables WAL mode.
async fn create_sqlite(url: &str) -> anyhow::Result<()> {
    let options = SqliteConnectOptions::from_str(url)?
        .create_if_missing(true)
        .journal_mode(SqliteJournalMode::Wal)
        .busy_timeout(Duration::from_secs(5));

    let _ = SqlitePoolOptions::new().connect_with(options).await?;
    Ok(())
}

const MIGRATION_FILES: [(&str, &str); 4] = [
    (
        "20260531175615_create_clients.up.sql",
        include_str!("../../../migrations/20260531175615_create_clients.up.sql"),
    ),
    (
        "20260531175615_create_clients.down.sql",
        include_str!("../../../migrations/20260531175615_create_clients.down.sql"),
    ),
    (
        "20260911062958_add_file_privacy.up.sql",
        include_str!("../../../migrations/20260911062958_add_file_privacy.up.sql"),
    ),
    (
        "20260911062958_add_file_privacy.down.sql",
        include_str!("../../../migrations/20260911062958_add_file_privacy.down.sql"),
    ),
];

/// Run migrations for MySQL.
///
/// MySQL doesn't support `BYTEA` or auto-incrementing `INTEGER PRIMARY KEY`
/// without `AUTO_INCREMENT`, so we embed the SQL at compile time, preprocess it,
/// write to a temp directory, then run via [`Migrator`].
async fn run_mysql_migrations(pool: &DbPool) -> anyhow::Result<()> {
    let temp_dir = std::env::temp_dir().join("ppdrive_migrations_mysql");
    std::fs::create_dir_all(&temp_dir)?;

    for (filename, content) in &MIGRATION_FILES {
        let content = content
            .replace("BYTEA", "BLOB")
            .replace("INTEGER PRIMARY KEY", "INTEGER PRIMARY KEY AUTO_INCREMENT");
        std::fs::write(temp_dir.join(filename), content)?;
    }

    let migrator = Migrator::new(temp_dir.clone()).await?;
    migrator.run(pool).await?;

    let _ = std::fs::remove_dir_all(&temp_dir);
    Ok(())
}

/// Run migrations for PostgreSQL.
///
/// Postgres requires `GENERATED BY DEFAULT AS IDENTITY` on primary key columns
/// for auto-increment. We preprocess the SQL at runtime via [`Migrator`].
async fn run_postgres_migrations(pool: &DbPool) -> anyhow::Result<()> {
    let temp_dir = std::env::temp_dir().join("ppdrive_migrations_postgres");
    std::fs::create_dir_all(&temp_dir)?;

    for (filename, content) in &MIGRATION_FILES {
        let content = content
            .replace("INTEGER PRIMARY KEY", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        std::fs::write(temp_dir.join(filename), content)?;
    }

    let migrator = Migrator::new(temp_dir.clone()).await?;
    migrator.run(pool).await?;

    let _ = std::fs::remove_dir_all(&temp_dir);
    Ok(())
}
