[package]
name = "ppd_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
tracing = "0.1.41"
tokio = { version = "1.47.1", features = ["fs"] }
toml = "0.9.5"
chacha20poly1305 = "0.10.1"
