[package]
name = "ppd_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
clap.workspace = true
serde = {workspace = true, features = ["derive"]}
tokio = { workspace = true, features = ["fs", "io-util"] }
toml = "0.9.5"
chacha20poly1305 = "0.10.1"
libloading = "0.8.8"
