[package]
name = "ppd_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {workspace = true, features = ["derive"]}
tracing.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
toml = "0.9.5"
chacha20poly1305 = "0.10.1"
