name: Build & Push Docker Images

on:
  push:
    branches:
      - 'deploy'
    # tags:
      # - 'v*'

  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKER_USER: prodbyola 
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push with Compose
        run: |
          # Replace image names with tag
          sed -i "s|image: ${DOCKER_USER}/\(.*\):.*|image: ${DOCKER_USER}/\1:${IMAGE_TAG}|g" compose.yml

          cp .env.example .env

          docker compose build
          docker compose push
