name: Build and Deploy ppdocs

on:
  push:
    branches:
      - main # or your deployment branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for Bun)
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0 # or your preferred version

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies and build
        working-directory: ./ppdocs
        run: |
          bun install
          bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ppdocs/build
