name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TARGET: x86_64-pc-windows-gnu

permissions:
  contents: write 

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install vcpkg and libpq
        run: |
          git clone https://github.com/microsoft/vcpkg.git

          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install libpq

          cd ..

      - name: Build release
        run: cargo build --release --target ${{ env.BUILD_TARGET }}

      - name: Rename binary
        run: |
          BIN_NAME=ppdrive
          mkdir -p dist
          cp target/${{ env.BUILD_TARGET }}/release/$BIN_NAME dist/${BIN_NAME}-${{ env.BUILD_TARGET }}

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
