name: Cross-compile & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          # - x86_64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross

      - name: Build with cross (custom Docker image with OpenSSL)
        run: cross build --release --target ${{ matrix.target }}
        env:
          CROSS_DOCKER_IMAGE: 'prodbyola/cross-openssl:latest'

      - name: Rename binary
        run: |
          BIN_NAME=ppdrive
          EXT=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then EXT=".exe"; fi
          mkdir -p dist
          cp target/${{ matrix.target }}/release/$BIN_NAME$EXT dist/${BIN_NAME}-${{ matrix.target }}$EXT

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
