name: Release (Linux)

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TARGET: x86_64-unknown-linux-gnu

permissions:
  contents: write 

jobs:
  build:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with cross
        run: cargo build --release --target ${{ env.BUILD_TARGET }}

      - name: Rename binary
        run: |
          BIN_NAME=ppdrive
          mkdir -p dist
          cp target/${{ env.BUILD_TARGET }}/release/$BIN_NAME dist/${BIN_NAME}-${{ env.BUILD_TARGET }}

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
