name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TARGET: x86_64-pc-windows-gnu

permissions:
  contents: write 

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            git
            make
          update: true

      - name: Install psql
        run: |
          cargo add serde@0.9.100 --features vendored 
          cargo add pq-sys@0.6 --features bundled
          
      - name: Install openssl
        run: pacman -S openssl-devel pkgconf

      - name: Build release
        run: cargo build --release --target ${{ env.BUILD_TARGET }}

      - name: Rename binary
        run: |
          BIN_NAME=ppdrive
          mkdir -p dist
          cp target/${{ env.BUILD_TARGET }}/release/$BIN_NAME dist/${BIN_NAME}-${{ env.BUILD_TARGET }}

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
