name: Release rest_client

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.0.0

permissions:
  contents: write

env:
  LIB_NAME: rest_client

jobs:
  build:
    name: Build rest_client Library
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_ext: .so
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin_ext: .dll
          - os: macos-latest
            target: x86_64-apple-darwin
            bin_ext: .dylib

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build Library
        run: |
          cargo build -p ${{ env.LIB_NAME }} --release --target ${{ matrix.target }}

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir -p artifacts
          LIB_OUTPUT="${{ env.LIB_NAME }}${{ matrix.bin_ext }}"

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/$LIB_OUTPUT artifacts/$LIB_OUTPUT
          else
            cp target/${{ matrix.target }}/release/lib$LIB_OUTPUT artifacts/$LIB_OUTPUT
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LIB_NAME }}-${{ matrix.target }}
          path: artifacts/

  release:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display downloaded files (debug)
        run: ls -R artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}

          files: |
            artifacts/**/*
          prerelease: ${{ contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
