name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-release:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: linux-x86_64
            bin_ext:

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows-x86_64
            bin_ext: .exe

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: macos-x86_64
            bin_ext:

          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: macos-arm64
            bin_ext:

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Build binaries
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binaries
        shell: bash
        run: |
          mkdir -p package

          cp target/${{ matrix.target }}/release/ppdrive${{ matrix.bin_ext }} package/
          cp target/${{ matrix.target }}/release/server${{ matrix.bin_ext }} package/

          mkdir -p dist

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            powershell -Command "Compress-Archive -Path package\\* -DestinationPath dist\\${{ matrix.artifact_name }}"
          else
            tar -czvf dist/${{ matrix.artifact_name }} -C package .
          fi

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/**/*.tar.gz
            dist/**/*.zip

          body: |
            # 🚀 PPDRIVE Pre-Release Notes
            **Version:** ${GITHUB_REF_NAME}
            **Date:** June 2026
            
            ## What’s New
            - Cli Tool
            - Resumable uploads
            - Serving static folders
            - And several others
            
            ## ⚠️ Notes
            
            This is a **prerelease build**, intended for early adopters and internal testing.
            Feedback and bug reports are highly appreciated as we prepare for the first stable release.

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
