name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TARGET: x86_64-pc-windows-gnu

permissions:
  contents: write 

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MSYS2 and dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-gcc

      - name: Set environment variables for OpenSSL
        run: |
          echo "OPENSSL_DIR=C:/msys64/mingw64" >> $env:GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $env:GITHUB_ENV
          echo "PKG_CONFIG_PATH=C:/msys64/mingw64/lib/pkgconfig" >> $env:GITHUB_ENV
          echo "C:/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install psql
        run: |
          cargo add serde@0.9.100 --features vendored 
          cargo add pq-sys@0.6 --features bundled
          
      - name: Build with MSYS2 shell
        run: |
          cargo build --release --target ${{ env.BUILD_TARGET }}

      - name: Rename binary
        run: |
          BIN_NAME=ppdrive.exe
          mkdir -p dist
          cp target/${{ env.BUILD_TARGET }}/release/$BIN_NAME dist/${BIN_NAME}-${{ env.BUILD_TARGET }}

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
