name: Release

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.0.0

permissions:
  contents: write # Required to create releases

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ppdrive-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ppdrive-windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ppdrive-macos

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename Binary
        run: |
          mkdir dist
          BIN_NAME=ppdrive
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            BIN_NAME=ppdrive.exe
          fi
          cp target/${{ matrix.target }}/release/$BIN_NAME dist/${{ matrix.artifact_name }}
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
