name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TARGET: x86_64-pc-windows-gnu

permissions:
  contents: write 

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install OpenSSL
        run: choco install openssl.light -y

      - name: Add OpenSSL to PATH
        run: |
          $opensslPath = "C:\Program Files\OpenSSL-Win64\bin"
          echo "$opensslPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify OpenSSL installation
        run: openssl version

      - name: Install psql
        run: |
          cargo add serde@0.9.100 --features vendored 
          cargo add pq-sys@0.6 --features bundled
          
      - name: Build release
        run: cargo build --release --target ${{ env.BUILD_TARGET }}

      - name: Rename binary
        run: |
          BIN_NAME=ppdrive
          mkdir -p dist
          cp target/${{ env.BUILD_TARGET }}/release/$BIN_NAME dist/${BIN_NAME}-${{ env.BUILD_TARGET }}

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
