name: Release

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    name: Build and Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ppdrive-linux.tar.gz
            bin_name: ppdrive
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ppdrive-windows.zip
            bin_name: ppdrive.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ppdrive-macos.tar.gz
            bin_name: ppdrive

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare Release Package
        run: |
          mkdir -p package

          cp target/${{ matrix.target }}/release/${{ matrix.bin_name }} package/
          cp -r migrations package/
          cp ppd_config.toml package/

          mkdir -p dist

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            powershell -Command "Compress-Archive -Path package\\* -DestinationPath dist\\${{ matrix.artifact_name }}"
          else
            tar -czvf dist/${{ matrix.artifact_name }} -C package .
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.{tar.gz,zip}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
